/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/component/addQuickEntranceDialog': RouteRecordInfo<'/component/addQuickEntranceDialog', '/component/addQuickEntranceDialog', Record<never, never>, Record<never, never>>,
    '/error/notPage': RouteRecordInfo<'/error/notPage', '/error/notPage', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/page/func/keepScore/': RouteRecordInfo<'/page/func/keepScore/', '/page/func/keepScore', Record<never, never>, Record<never, never>>,
    '/page/func/keepScore/component/keepScoreType': RouteRecordInfo<'/page/func/keepScore/component/keepScoreType', '/page/func/keepScore/component/keepScoreType', Record<never, never>, Record<never, never>>,
    '/page/func/keepScore/component/startKeepScore': RouteRecordInfo<'/page/func/keepScore/component/startKeepScore', '/page/func/keepScore/component/startKeepScore', Record<never, never>, Record<never, never>>,
    '/page/menu/setting/': RouteRecordInfo<'/page/menu/setting/', '/page/menu/setting', Record<never, never>, Record<never, never>>,
    '/page/menu/setting/component/addDialog': RouteRecordInfo<'/page/menu/setting/component/addDialog', '/page/menu/setting/component/addDialog', Record<never, never>, Record<never, never>>,
    '/page/menu/setting/component/editDialog': RouteRecordInfo<'/page/menu/setting/component/editDialog', '/page/menu/setting/component/editDialog', Record<never, never>, Record<never, never>>,
    '/page/student/list/': RouteRecordInfo<'/page/student/list/', '/page/student/list', Record<never, never>, Record<never, never>>,
    '/page/student/list/component/addDialog': RouteRecordInfo<'/page/student/list/component/addDialog', '/page/student/list/component/addDialog', Record<never, never>, Record<never, never>>,
    '/page/student/list/component/echarttDialog': RouteRecordInfo<'/page/student/list/component/echarttDialog', '/page/student/list/component/echarttDialog', Record<never, never>, Record<never, never>>,
    '/page/student/list/component/itemDialog': RouteRecordInfo<'/page/student/list/component/itemDialog', '/page/student/list/component/itemDialog', Record<never, never>, Record<never, never>>,
    '/page/user/list/': RouteRecordInfo<'/page/user/list/', '/page/user/list', Record<never, never>, Record<never, never>>,
    '/page/user/role/': RouteRecordInfo<'/page/user/role/', '/page/user/role', Record<never, never>, Record<never, never>>,
    '/page/user/role/component/addDialog': RouteRecordInfo<'/page/user/role/component/addDialog', '/page/user/role/component/addDialog', Record<never, never>, Record<never, never>>,
    '/page/user/role/component/editDialog': RouteRecordInfo<'/page/user/role/component/editDialog', '/page/user/role/component/editDialog', Record<never, never>, Record<never, never>>,
    '/userInfo': RouteRecordInfo<'/userInfo', '/userInfo', Record<never, never>, Record<never, never>>,
  }
}
